name: Build and Deploy

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 10.13
    - name: Install dependencies
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build

